# Generated by Django 5.0.3 on 2024-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_stuff',
            field=models.BooleanField(default=True),
        ),
    ]
