# Generated by Django 5.0.3 on 2024-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
